function points = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  points = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  numeric data.
%
%  points = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  points = importfile("\\store-01.hpi.uni-potsdam.de\home\vLiDAR\acer_campestre_young_976000_ub_stationary4_90.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Apr-2024 11:49:17

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["x", "y", "z", "Var4", "Var5", "Var6"];
opts.SelectedVariableNames = ["x", "y", "z"];
opts.VariableTypes = ["double", "double", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
points = readtable(filename, opts);

%% Convert to output type
points = table2array(points);
end